var success_msg = {
  registered: "User registered successfully",
  login: "Login successful",
  passwordLink: "Password reset link has been sent to your email",
  passwordChange: "Password changed successfully",
  logout: "User logged out successfully!",
  updateProfile: "Profile updated successfully!",
  passwordUpdate: "Password updated successfully.",
  otpSend: "OTP sent successfully",
  otpVerify: "Otp verified successfully",
  otpResend: "OTP resent successfully",
  userList:"User list fatch successfully",
  cms:"CMS list fatch successfully",
  userDetail:"User detail get successfully.",
  logOut:"User logout successfully",
  driverStatusChange: "Driver status changed successfully",
  userStatusChange: "User status changed successfully",
  dashboardData:"Dashboard data fatch successfully.",
  faqList:"FAQ list fatch successfully",
  faqAdd:"FAQ added successfully",
  faqEdit:"FAQ edited successfully",
  faqDelete:"FAQ deleted successfully",
  categoryList:"Category list fatch successfully",
  categoryAdd:"Category added successfully",
  categoryEdit:"Category edited successfully",
  categoryDelete:"Category deleted successfully",
  productList:"Product list fatch successfully",
  productAdd:"Product added successfully",
  productEdit:"Product edited successfully",
  contactUsDetail:"Contact us detail get successfully.",
  contactUsDelete:"Contact us entry deleted successfully",
  contactUsList:"Contact us list fatch successfully",
  categoryStatusChange: "Category status changed successfully",
  productStatusChange: "Product status changed successfully",
  citiesList:"Cities list fetched successfully",
  citiesCreate: "City created successfully",
  citiesUpdate: "City updated successfully",
  citiesDelete: "City deleted successfully",
  cityView:"City detail fetched successfully",
  cityStatusChange: "City status changed successfully",
  postalCodeList:"Postal Code list fetched successfully",
  postalCodeCreate: "Postal Code created successfully",
  postalCodeUpdate: "Postal Code updated successfully",
  postalCodeDelete: "Postal Code deleted successfully",
  postalCodeStatusChange: "Postal Code status changed successfully",
  postalCodeView:"Postal Code detail fetched successfully",
  codStatusChange: "Cash on Delivery status changed successfully",
  totalOrderList: "Total order list fetched successfully",
  bookingsList: "Bookings list fetched successfully",
};

var failed_msg = {
  userNotFound: "User not found",
  invalidCrd:"Invalid Credentials",
  accNotAppoved:"Account not approved yet.Please wait",
  invalidPassword: "Invalid password",
  noAccWEmail: "No account exists with this email",
  pwdNoMatch: "Passwords do not match!",
  userIdReq: "User ID is required.",
  incorrectCurrPwd: "Incorrect current password.",
  tokReq: "Token is required!",
  invTok: "Invalid token!",
  invalidOtp: "Invalid OTP",
};

var error_msg = {
  regUser: "Error registering user",
  loguser: "Error during login",
  forgPwdErr: "Forgot password error",
  resetPwdErr: "Reset password error",
  chngPwdErr: "Error while changing the password",
  logoutErr: "Logout error",
  updPrfErr: "Error while updating profile",
  tokenNotPrv: "Token is not provided!",
  forPwdTokVer: "Forgot password token verification error!",
  pwdResTokExp: "Password reset token is invalid or has expired",
  otpSendErr: "Error while sending the otp",
  otpVerErr: "Error while verifying the otp",
  otpResErr: "Failed to resend OTP",
  addBlogErr: "Failed to add blog",
  intSerErr: "Internal server error",
};

module.exports = {
  success_msg: success_msg,
  failed_msg: failed_msg,
  error_msg: error_msg,
};
